# Generated by Django 4.2.16 on 2026-01-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_rename_body_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new_field',
        ),
    ]
